name: Test

on:
  push:
    branches: [deus/test]

jobs:
  test:
    name: Deus Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          cp docker/dev/.env.example docker/dev/.env
          cp server/.env.example server/.env
          docker compose up -d
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v2
        id: root-npm-cache
        with:
          path: 'node_modules'
          key: root-npm-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: client-npm-cache
        with:
          path: 'client/node_modules'
          key: client-npm-${{ hashFiles('client/package-lock.json') }}
      - uses: actions/cache@v2
        id: server-npm-cache
        with:
          path: 'server/node_modules'
          key: server-npm-${{ hashFiles('server/package-lock.json') }}
      - run: npm install
        if: steps.root-npm-cache.outputs.cache-hit != 'true'
      - run: npm install --prefix client
        if: steps.client-npm-cache.outputs.cache-hit != 'true'
      - run: npm install --prefix server
        if: steps.server-npm-cache.outputs.cache-hit != 'true'
      - run: cp server/prisma/.env.example server/prisma/.env
      - run: npm run migrate:dev:createonly --prefix server -- --name deus
      - run: npm run generate
      - run: npm run lint:fix
      - run: npm run typecheck
      - run: cp client/.env.example client/.env
      - run: npm test
      - run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "Formatted"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD
          fi
          git push https://${{ secrets.PAT }}@github.com/${{ github.repository }} HEAD:main
